class AddTestImageData < ActiveRecord::Migration
  def self.up

Image.create([

        {:file_name=> 'assets/medium/IMG_7312.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7313.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7314.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7316.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7317.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7318.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7319.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7320.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7321.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7322.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7323.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7324.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7325.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7327.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7328.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7329.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7330.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7331.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7333.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7335.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7337.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7341.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7342.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7343.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7344.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7345.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7346.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7347.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7348.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7353.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7354.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7355.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7356.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7357.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7358.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7359.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7361.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7364.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7365.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7366.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7367.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7368.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7369.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7370.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7371.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7372.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7373.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7374.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7375.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7376.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7377.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7378.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7379.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7380.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7381.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7382.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7383.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7384.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7385.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7386.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7391.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7392.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7393.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7394.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7396.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7397.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7399.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7400.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7401.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7402.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7403.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7404.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7405.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7406.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7407.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7408.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7409.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7410.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7411.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7412.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7414.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7415.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7416.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7417.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7418.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7419.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7422.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7424.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7425.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7426.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7427.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7428.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7429.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7431.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7433.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7434.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7435.jpg',:group=> 1},
        {:file_name=> 'assets/medium/IMG_7436.jpg',:group=> 1}
    ])

    
  end

  def self.down

    Image.delete_all

  end
end
